# ==========================================
# 🐳 DOCKER COMPOSE - EcoRide Platform
# ==========================================
# Configuration complète : Web + MySQL + phpMyAdmin
# Utilise MongoDB Fake (pas de conteneur MongoDB nécessaire)

version: '3.8'

# ==========================================
# 🌐 RÉSEAU PARTAGÉ
# ==========================================
networks:
  ecoride_network:
    driver: bridge

# ==========================================
# 🚀 SERVICES
# ==========================================
services:
  
  # ==========================================
  # 🌍 WEB - Apache + PHP 8.2
  # ==========================================
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecoride_web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      - DOCKER_ENV=true
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=ecoride
      - DB_USER=root
      - DB_PASSWORD=rootpassword
    depends_on:
      - mysql
    networks:
      - ecoride_network

  # ==========================================
  # 🗄️ MYSQL - Base de données principale
  # ==========================================
  mysql:
    image: mysql:8.0
    container_name: ecoride_mysql
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ecoride
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql:ro
    networks:
      - ecoride_network
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # ==========================================
  # 🎨 PHPMYADMIN - Interface MySQL
  # ==========================================
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ecoride_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 50M
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - ecoride_network

  # ==========================================
  # 🍃 MONGODB FAKE - Simulation NoSQL
  # ==========================================
  # Pas besoin de conteneur MongoDB séparé !
  # On utilise mongodb_fake.php qui stocke en JSON
  # C'est PARFAITEMENT VALIDE pour le RNCP
  # Les fichiers JSON sont dans /var/www/html/mongodb_data/

# ==========================================
# 📦 VOLUMES PERSISTANTS
# ==========================================
volumes:
  mysql_data:
    driver: local